### ISSUE TITLE
per label set policy is wrong

### ISSUE THREAD

**Issue by k8-scalar** [k8-scalar/grasshopper#5]
It seems per labelset security groups are created with default egress rules to 0.0.0.0.

```
ubuntu@test-master:~/grasshopper/experiments/microservices$ kubectl delete networkpolicies. --all -n test
networkpolicy.networking.k8s.io "ts-locust-policy" deleted
networkpolicy.networking.k8s.io "ts-policy" deleted
ubuntu@test-master:~/grasshopper/experiments/microservices$ helm delete ts -n test
release "ts" uninstalled
ubuntu@test-master:~/grasshopper/experiments/microservices$ kubectl create -f teastore-policy.yml
networkpolicy.networking.k8s.io/ts-policy created
ubuntu@test-master:~/grasshopper/experiments/microservices$ kubectl create -f teastore-locust-policy.yml
networkpolicy.networking.k8s.io/ts-locust-policy created
ubuntu@test-master:~/grasshopper/experiments/microservices$ helm install ts -n test teastore-helm/
NAME: ts
LAST DEPLOYED: Tue Mar 25 11:46:47 2025
NAMESPACE: test
STATUS: deployed
REVISION: 1
TEST SUITE: None
ubuntu@test-master:~/grasshopper/experiments/microservices$ ls
Kubernetes-Recap.pptx  deny-all.yml  service-new.yaml  teastore-architecture.pdf  teastore-locust-policy.yml  ts-networkpolicy.yaml
Session1.pptx          readme.md     service.yaml      teastore-helm              teastore-policy.yml         µ
ubuntu@test-master:~/grasshopper/experiments/microservices$ vi teastore-locust-policy.yml
ubuntu@test-master:~/grasshopper/experiments/microservices$ kubectl get pods -n test
NAME                                    READY   STATUS    RESTARTS   AGE
teastore-auth-596c4f665f-t5ljv          1/1     Running   0          2m26s
teastore-db-595c4d97b7-m276j            0/1     Pending   0          2m26s
teastore-image-5c9b5dfddc-cq9hb         1/1     Running   0          2m26s
teastore-locust-5886c79cb4-ppcb4        0/1     Pending   0          2m25s
teastore-persistence-6676cc54cd-vx5vh   1/1     Running   0          2m26s
teastore-recommender-6cfcc6f5c5-n2vpg   1/1     Running   0          2m25s
teastore-registry-69dd9d75c6-7l9m2      1/1     Running   0          2m26s
teastore-webui-7954544c7c-2xdsv         1/1     Running   0          2m25s
```

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ts-locust-policy
  namespace: test
spec:
  podSelector:
    matchLabels:
      run: teastore-locust
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    - podSelector:
        matchLabels:
          app: teastore
    ports:
    - protocol: TCP
      port: 8080
    - protocol: TCP
      port: 3306
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 9053
```
```
Manage Security Group Rules: SG-run:teastore-locust (aed16a62-5532-4811-911a-324cf6b7c856)
Displaying 2 items
	Direction
	Ether Type
	IP Protocol
	Port Range
	Remote IP Prefix
	Remote Security Group
	Description
	Actions
	Egress 	IPv4 	Any 	Any 	0.0.0.0/0 	- 	- 	
	Egress 	IPv6 	Any 	Any 	::/0 	- 	- 	
Displaying 2 items
```
