### ISSUE TITLE
per label set policy to kubedns pods is not  processed

### ISSUE THREAD

**Issue by k8-scalar** [k8-scalar/grasshopper#6]
De kubedns pods draaien al.  
Als onderstaande network policy wordt gemaakt

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ts-policy
  namespace: test
spec:
  podSelector:
    matchLabels:
      app: teastore
  policyTypes:
  - Egress
  - Ingress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    - podSelector:
        matchLabels:
          app: teastore
    ports:
    - protocol: TCP
      port: 8080
    - protocol: TCP
      port: 3306
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 9053
  ingress:
  - from:
    - podSelector:
        matchLabels:
          run: teastore-locust
    - podSelector:
        matchLabels:
          app: teastore
    ports:
    - protocol: TCP
      port: 8080
    - protocol: TCP
      port: 3306
```

wordt de security group correct aangemaakt:

```
SG-k8s-app:kube-dnskubernetes.io/metadata.name:kube-system | 064ce0e7-d02d-4350-bc7f-4de14cb015d3 | Security Group for SG-k8s-app:kube-dnskubernetes.io/metadata.name:kube-system | False |  
```

maar deze wordt niet attached.

Als ik de kubedns pod toevoeg wortdt de security group ook niet toegevoegd

```
Pod(name=coredns-5dd5756b68-m89x6, label_set=LabelSet(labels={'k8s-app': 'kube-dns', 'pod-template-hash': '5dd5756b68'}), node=Node(name=test-master2)
Pod coredns-5dd5756b68-m89x6 already exists in the cluster.
Pod(name=coredns-5dd5756b68-m89x6, label_set=LabelSet(labels={'k8s-app': 'kube-dns', 'pod-template-hash': '5dd5756b68'}), node=Node(name=test-master2)
Pod coredns-5dd5756b68-m89x6 already exists in the cluster.
Pod(name=coredns-5dd5756b68-m89x6, label_set=LabelSet(labels={'k8s-app': 'kube-dns', 'pod-template-hash': '5dd5756b68'}), node=Node(name=test-master2)
Pod coredns-5dd5756b68-m89x6 already exists in the cluster.
Pod(name=coredns-5dd5756b68-m89x6, label_set=LabelSet(labels={'k8s-app': 'kube-dns', 'pod-template-hash': '5dd5756b68'}), node=Node(name=test-master2)
Pod coredns-5dd5756b68-m89x6 already exists in the cluster.
Pod(name=coredns-5dd5756b68-m89x6, label_set=LabelSet(labels={'k8s-app': 'kube-dns', 'pod-template-hash': '5dd5756b68'}), node=Node(name=test-master2)
```
```
Name
   test-master2

Security Groups

SG_test-master2

        ALLOW IPv4 3306/tcp from SG_test-master2
        ALLOW IPv4 3306/tcp to SG_test-master2
        ALLOW IPv4 53/tcp to SG_test-master2
        ALLOW IPv4 8080/tcp to SG_test-master2
        ALLOW IPv4 53/udp to SG_test-master2
        ALLOW IPv4 9053/tcp to SG_test-master2
        ALLOW IPv4 8080/tcp from SG_test-master2

workerSG

        ALLOW IPv4 53/udp from c73d7f9b-5e7f
        ALLOW IPv4 9053/tcp to workerSG
        ALLOW IPv4 53/udp to c73d7f9b-5e7f
        ALLOW IPv4 2379/tcp to c73d7f9b-5e7f
        ALLOW IPv4 10259/tcp to c73d7f9b-5e7f
        ALLOW IPv4 9053/tcp to c73d7f9b-5e7f
        ALLOW IPv4 443/tcp to c73d7f9b-5e7f
        ALLOW IPv4 9053/tcp to 0.0.0.0/0
        ALLOW IPv4 22/tcp to c73d7f9b-5e7f
        ALLOW IPv4 6443/tcp to c73d7f9b-5e7f
        ALLOW IPv4 22/tcp from c73d7f9b-5e7f
        ALLOW IPv4 10250/tcp from c73d7f9b-5e7f
        ALLOW IPv4 10250/tcp to c73d7f9b-5e7f
        ALLOW IPv4 10259/tcp from c73d7f9b-5e7f
        ALLOW IPv4 179/tcp to c73d7f9b-5e7f
        ALLOW IPv4 53/tcp to c73d7f9b-5e7f

SG-app:teastore

        ALLOW IPv4 3306/tcp to 064ce0e7-d02d
        ALLOW IPv4 8080/tcp from SG-app:teastore
        ALLOW IPv4 53/tcp to 064ce0e7-d02d
        ALLOW IPv4 53/udp to SG-app:teastore
        ALLOW IPv4 8080/tcp from aed16a62-5532
        ALLOW IPv4 3306/tcp to SG-app:teastore
        ALLOW IPv4 3306/tcp from SG-app:teastore
        ALLOW IPv4 9053/tcp to 064ce0e7-d02d
        ALLOW IPv4 3306/tcp from aed16a62-5532
        ALLOW IPv4 8080/tcp to SG-app:teastore
        ALLOW IPv4 to 0.0.0.0/0
        ALLOW IPv4 53/udp to 064ce0e7-d02d
        ALLOW IPv4 8080/tcp to 064ce0e7-d02d
        ALLOW IPv6 to ::/0
        ALLOW IPv4 53/tcp to SG-app:teastore
        ALLOW IPv4 9053/tcp to SG-app:teastore
```
