### ISSUE TITLE
per sg security groups are not deleted

### ISSUE THREAD

**Issue by k8-scalar** [k8-scalar/grasshopper#9]
```
ubuntu@test-master:~/grasshopper/experiments/microservices$ kubectl create -f teastore-webui.yaml -n test
deployment.apps/teastore-locust created
deployment.apps/teastore-db created
ubuntu@test-master:~/grasshopper/experiments/microservices$ kubectl create -f teastore-locust-policy.yml

networkpolicy.networking.k8s.io/ts-locust-policy created
ubuntu@test-master:~/grasshopper/experiments/microservices$
ubuntu@test-master:~/grasshopper/experiments/microservices$ kubectl get pods -n test -o wide
NAME                               READY   STATUS    RESTARTS   AGE   IP               NODE            NOMINATED NODE   READINESS GATES
teastore-db-6cc678c78f-6sjj2       1/1     Running   0          60s   192.168.101.65   test-master2    <none>           <none>
teastore-locust-5886c79cb4-bqx87   1/1     Running   0          60s   192.168.68.10    test-worker-2   <none>           <none>
ubuntu@test-master:~/grasshopper/experiments/microservices$ vi teastore-locust-policy.yml
ubuntu@test-master:~/grasshopper/experiments/microservices$ kubectl create -f teastore-policy.yml
networkpolicy.networking.k8s.io/ts-policy created
ubuntu@test-master:~/grasshopper/experiments/microservices$ kubectl delete -f teastore-locust-policy.yml
networkpolicy.networking.k8s.io "ts-locust-policy" deleted
ubuntu@test-master:~/grasshopper/experiments/microservices$ kubectl get pods -n test -o wide
NAME                               READY   STATUS    RESTARTS   AGE     IP               NODE            NOMINATED NODE   READINESS GATES
teastore-db-6cc678c78f-6sjj2       1/1     Running   0          4m42s   192.168.101.65   test-master2    <none>           <none>
teastore-locust-5886c79cb4-bqx87   1/1     Running   0          4m42s   192.168.68.10    test-worker-2   <none>           <none>
ubuntu@test-master:~/grasshopper/experiments/microservices$ kubectl get networkpolicies. -n test
NAME        POD-SELECTOR   AGE
ts-policy   app=teastore   2m22s
```
```
Pods:
  - Pod(name=appgroup-controller-7d8f567dd4-hpl2x, label_set=LabelSet(labels={'app': 'appgroup-controller', 'pod-template-hash': '7d8f567dd4'}), node=Node(name=test-master)
  - Pod(name=diktyo-scheduler-5f444d99b4-ggwd4, label_set=LabelSet(labels={'component': 'scheduler', 'pod-template-hash': '5f444d99b4', 'tier': 'control-plane'}), node=Node(name=test-master)
  - Pod(name=networktopology-controller-758f6b75dc-2sfz5, label_set=LabelSet(labels={'app': 'networktopology-controller', 'pod-template-hash': '758f6b75dc'}), node=Node(name=test-master)
  - Pod(name=scheduler-plugins-controller-7b58867ffc-s9zbp, label_set=LabelSet(labels={'app': 'scheduler-plugins-controller', 'pod-template-hash': '7b58867ffc'}), node=Node(name=test-master)
  - Pod(name=calico-kube-controllers-644d7f5966-szvfx, label_set=LabelSet(labels={'k8s-app': 'calico-kube-controllers', 'pod-template-hash': '644d7f5966'}), node=Node(name=test-master)
  - Pod(name=calico-node-67xj5, label_set=LabelSet(labels={'controller-revision-hash': '78fb6b4856', 'k8s-app': 'calico-node', 'pod-template-generation': '1'}), node=Node(name=test-master)
  - Pod(name=calico-node-6w52d, label_set=LabelSet(labels={'controller-revision-hash': '78fb6b4856', 'k8s-app': 'calico-node', 'pod-template-generation': '1'}), node=Node(name=test-master2)
  - Pod(name=calico-node-ntc7c, label_set=LabelSet(labels={'controller-revision-hash': '78fb6b4856', 'k8s-app': 'calico-node', 'pod-template-generation': '1'}), node=Node(name=test-worker-2)
  - Pod(name=calico-node-qklsr, label_set=LabelSet(labels={'controller-revision-hash': '78fb6b4856', 'k8s-app': 'calico-node', 'pod-template-generation': '1'}), node=Node(name=test-worker-1)
  - Pod(name=calico-node-whlx8, label_set=LabelSet(labels={'controller-revision-hash': '78fb6b4856', 'k8s-app': 'calico-node', 'pod-template-generation': '1'}), node=Node(name=test-worker-4)
  - Pod(name=coredns-5dd5756b68-cp5xt, label_set=LabelSet(labels={'k8s-app': 'kube-dns', 'pod-template-hash': '5dd5756b68'}), node=Node(name=test-worker-2)
  - Pod(name=coredns-5dd5756b68-m89x6, label_set=LabelSet(labels={'k8s-app': 'kube-dns', 'pod-template-hash': '5dd5756b68'}), node=Node(name=test-master2)
  - Pod(name=coredns-5dd5756b68-qsgsg, label_set=LabelSet(labels={'k8s-app': 'kube-dns', 'pod-template-hash': '5dd5756b68'}), node=Node(name=test-master)
  - Pod(name=etcd-test-master, label_set=LabelSet(labels={'component': 'etcd', 'tier': 'control-plane'}), node=Node(name=test-master)
  - Pod(name=kube-apiserver-test-master, label_set=LabelSet(labels={'component': 'kube-apiserver', 'tier': 'control-plane'}), node=Node(name=test-master)
  - Pod(name=kube-controller-manager-test-master, label_set=LabelSet(labels={'component': 'kube-controller-manager', 'tier': 'control-plane'}), node=Node(name=test-master)
  - Pod(name=kube-proxy-26x6b, label_set=LabelSet(labels={'controller-revision-hash': '8486c7d9cd', 'k8s-app': 'kube-proxy', 'pod-template-generation': '5'}), node=Node(name=test-worker-1)
  - Pod(name=kube-proxy-89qkx, label_set=LabelSet(labels={'controller-revision-hash': '8486c7d9cd', 'k8s-app': 'kube-proxy', 'pod-template-generation': '5'}), node=Node(name=test-master2)
  - Pod(name=kube-proxy-hxhtk, label_set=LabelSet(labels={'controller-revision-hash': '8486c7d9cd', 'k8s-app': 'kube-proxy', 'pod-template-generation': '5'}), node=Node(name=test-worker-4)
  - Pod(name=kube-proxy-wcbht, label_set=LabelSet(labels={'controller-revision-hash': '8486c7d9cd', 'k8s-app': 'kube-proxy', 'pod-template-generation': '5'}), node=Node(name=test-master)
  - Pod(name=kube-proxy-zz4pr, label_set=LabelSet(labels={'controller-revision-hash': '8486c7d9cd', 'k8s-app': 'kube-proxy', 'pod-template-generation': '5'}), node=Node(name=test-worker-2)
  - Pod(name=kube-scheduler-test-master, label_set=LabelSet(labels={'component': 'kube-scheduler', 'tier': 'control-plane'}), node=Node(name=test-master)
  - Pod(name=catalog-operator-6fbb6bd9bb-x4q6n, label_set=LabelSet(labels={'app': 'catalog-operator', 'pod-template-hash': '6fbb6bd9bb'}), node=Node(name=test-master2)
  - Pod(name=cc81cf81db961c19190a5d2d2f3aec43f7655b792d1b0f765cf120cc4dk5wsl, label_set=LabelSet(labels={'batch.kubernetes.io/controller-uid': 'a403be4b-d06d-440a-809b-09f58e7ffe56', 'batch.kubernetes.io/job-name': 'cc81cf81db961c19190a5d2d2f3aec43f7655b792d1b0f765cf120cc4d020dd', 'controller-uid': 'a403be4b-d06d-440a-809b-09f58e7ffe56', 'job-name': 'cc81cf81db961c19190a5d2d2f3aec43f7655b792d1b0f765cf120cc4d020dd', 'olm.managed': 'true'}), node=Node(name=test-master2)
  - Pod(name=d43d5200f751e3309fcea5cd9043ee3654cbc9d6a33d104f87c069b30bx8c4t, label_set=LabelSet(labels={'batch.kubernetes.io/controller-uid': '2db0dfd9-6956-4845-983b-7148a9696ad4', 'batch.kubernetes.io/job-name': 'd43d5200f751e3309fcea5cd9043ee3654cbc9d6a33d104f87c069b30bae1a1', 'controller-uid': '2db0dfd9-6956-4845-983b-7148a9696ad4', 'job-name': 'd43d5200f751e3309fcea5cd9043ee3654cbc9d6a33d104f87c069b30bae1a1', 'olm.managed': 'true'}), node=Node(name=test-master2)
  - Pod(name=olm-operator-574697c48b-rnthb, label_set=LabelSet(labels={'app': 'olm-operator', 'pod-template-hash': '574697c48b'}), node=Node(name=test-master2)
  - Pod(name=operatorhubio-catalog-jbgdh, label_set=LabelSet(labels={'catalogsource.operators.coreos.com/update': '', 'olm.catalogSource': 'operatorhubio-catalog', 'olm.managed': 'true', 'olm.pod-spec-hash': '2x1nBHsbQOubqsGtZedVVKLKuv3chn8Oxx6Yio'}), node=Node(name=test-worker-4)
  - Pod(name=packageserver-75998dd856-4cwvl, label_set=LabelSet(labels={'app': 'packageserver', 'pod-template-hash': '75998dd856'}), node=Node(name=test-master2)
  - Pod(name=packageserver-75998dd856-697pl, label_set=LabelSet(labels={'app': 'packageserver', 'pod-template-hash': '75998dd856'}), node=Node(name=test-worker-2)
  - Pod(name=nginx-deployment-854d7bb674-rl8sx, label_set=LabelSet(labels={'app': 'nginx', 'pod-template-hash': '854d7bb674'}), node=Node(name=test-master)
  - Pod(name=opa-758775bd55-6gkxh, label_set=LabelSet(labels={'app': 'opa', 'pod-template-hash': '758775bd55'}), node=Node(name=test-master)
  - Pod(name=everything-allowed-exec-pod-4, label_set=LabelSet(labels={'app': 'pentest'}), node=Node(name=test-master2)
  - Pod(name=hostpath-exec-pod, label_set=LabelSet(labels={'app': 'pentest'}), node=Node(name=test-worker-2)
  - Pod(name=spark-operator-69b84c8f48-l66x8, label_set=LabelSet(labels={'app.kubernetes.io/instance': 'spark-operator', 'app.kubernetes.io/name': 'spark-operator', 'pod-template-hash': '69b84c8f48'}), node=Node(name=test-master2)
  - Pod(name=test, label_set=LabelSet(labels={'run': 'test'}), node=Node(name=test-worker-1)
  - Pod(name=teastore-locust-5886c79cb4-bqx87, label_set=LabelSet(labels={'pod-template-hash': '5886c79cb4', 'run': 'teastore-locust'}), node=Node(name=test-worker-2)
  - Pod(name=teastore-db-6cc678c78f-6sjj2, label_set=LabelSet(labels={'app': 'teastore', 'pod-template-hash': '6cc678c78f', 'release': 'release-name', 'run': 'teastore-db'}), node=Node(name=test-master2)

Policies:
  - Policy(name=ts-policy, sel=LabelSet(labels={'app': 'teastore'}), allow=[
(LabelSet(labels={'run': 'teastore-locust'}), Traffic(direction=ingress, port=8080, protocol=TCP))
])
  - Policy(name=ts-policy, sel=LabelSet(labels={'app': 'teastore'}), allow=[
(LabelSet(labels={'run': 'teastore-locust'}), Traffic(direction=ingress, port=3306, protocol=TCP))
])
  - Policy(name=ts-policy, sel=LabelSet(labels={'app': 'teastore'}), allow=[
(LabelSet(labels={'app': 'teastore'}), Traffic(direction=ingress, port=8080, protocol=TCP))
])
  - Policy(name=ts-policy, sel=LabelSet(labels={'app': 'teastore'}), allow=[
(LabelSet(labels={'app': 'teastore'}), Traffic(direction=ingress, port=3306, protocol=TCP))
])
  - Policy(name=ts-policy, sel=LabelSet(labels={'app': 'teastore'}), allow=[
(LabelSet(labels={'kubernetes.io/metadata.name': 'kube-system', 'k8s-app': 'kube-dns'}), Traffic(direction=egress, port=8080, protocol=TCP))
])
  - Policy(name=ts-policy, sel=LabelSet(labels={'app': 'teastore'}), allow=[
(LabelSet(labels={'kubernetes.io/metadata.name': 'kube-system', 'k8s-app': 'kube-dns'}), Traffic(direction=egress, port=3306, protocol=TCP))
])
  - Policy(name=ts-policy, sel=LabelSet(labels={'app': 'teastore'}), allow=[
(LabelSet(labels={'kubernetes.io/metadata.name': 'kube-system', 'k8s-app': 'kube-dns'}), Traffic(direction=egress, port=53, protocol=TCP))
])
  - Policy(name=ts-policy, sel=LabelSet(labels={'app': 'teastore'}), allow=[
(LabelSet(labels={'kubernetes.io/metadata.name': 'kube-system', 'k8s-app': 'kube-dns'}), Traffic(direction=egress, port=53, protocol=UDP))
])
  - Policy(name=ts-policy, sel=LabelSet(labels={'app': 'teastore'}), allow=[
(LabelSet(labels={'kubernetes.io/metadata.name': 'kube-system', 'k8s-app': 'kube-dns'}), Traffic(direction=egress, port=9053, protocol=TCP))
])
  - Policy(name=ts-policy, sel=LabelSet(labels={'app': 'teastore'}), allow=[
(LabelSet(labels={'app': 'teastore'}), Traffic(direction=egress, port=8080, protocol=TCP))
])
  - Policy(name=ts-policy, sel=LabelSet(labels={'app': 'teastore'}), allow=[
(LabelSet(labels={'app': 'teastore'}), Traffic(direction=egress, port=3306, protocol=TCP))
])
  - Policy(name=ts-policy, sel=LabelSet(labels={'app': 'teastore'}), allow=[
(LabelSet(labels={'app': 'teastore'}), Traffic(direction=egress, port=53, protocol=TCP))
])
  - Policy(name=ts-policy, sel=LabelSet(labels={'app': 'teastore'}), allow=[
(LabelSet(labels={'app': 'teastore'}), Traffic(direction=egress, port=53, protocol=UDP))
])
  - Policy(name=ts-policy, sel=LabelSet(labels={'app': 'teastore'}), allow=[
(LabelSet(labels={'app': 'teastore'}), Traffic(direction=egress, port=9053, protocol=TCP))
])

Offending Policies:
  None

Security Groups:
  - SG_worker-1: SecurityGroup(id=0614e54e-8534-40c2-8fe2-5682d1ceb52c, name=SG_worker-1, remotes=)
  - netperf: SecurityGroup(id=0b326d7d-6d2c-4a13-97f4-3b87bb24f2bc, name=netperf, remotes=Rule(id=None, target=netperf, traffic=Traffic(direction=egress, port=12865, protocol=tcp)), Rule(id=None, target=netperf, traffic=Traffic(direction=ingress, port=8079, protocol=tcp)), Rule(id=None, target=netperf, traffic=Traffic(direction=ingress, port=12865, protocol=tcp)), Rule(id=None, target=netperf, traffic=Traffic(direction=egress, port=5001, protocol=tcp)), Rule(id=None, target=netperf, traffic=Traffic(direction=egress, port=8079, protocol=tcp)), Rule(id=None, target=netperf, traffic=Traffic(direction=ingress, port=5001, protocol=tcp)))
  - SG_worker-2: SecurityGroup(id=13c7fad3-b84c-4278-acdf-4324ec2a091a, name=SG_worker-2, remotes=)
  - SG_test-master2: SecurityGroup(id=19d2fe9d-9654-4781-bf5e-0ef1c886732a, name=SG_test-master2, remotes=Rule(id=44dd4642-3c1d-4251-b2d2-297104524fbf, target=SG_test-master2, traffic=Traffic(direction=ingress, port=8080, protocol=TCP)), Rule(id=201f094e-1e73-4729-9338-c9e99c0e1aca, target=SG_test-worker-2, traffic=Traffic(direction=ingress, port=3306, protocol=TCP)), Rule(id=9ac4e17a-b270-4e79-87f3-a2ce9fbb1f74, target=SG_test-master2, traffic=Traffic(direction=egress, port=3306, protocol=TCP)), Rule(id=1abc9e99-6b7e-4e03-8d1b-511521986910, target=SG_test-master2, traffic=Traffic(direction=egress, port=53, protocol=UDP)), Rule(id=84a303b7-4a93-4d51-8e41-a818e7b3b74b, target=SG_test-master2, traffic=Traffic(direction=egress, port=9053, protocol=TCP)), Rule(id=e59f5870-3b6f-46ad-b1d7-b7dd09ec2642, target=SG_test-master2, traffic=Traffic(direction=ingress, port=3306, protocol=TCP)), Rule(id=68726cf1-c286-4f0f-9eca-557710679a75, target=SG_test-master2, traffic=Traffic(direction=egress, port=53, protocol=TCP)), Rule(id=87854296-e18f-4182-8cf9-5f2f9dd2e0ad, target=SG_test-worker-2, traffic=Traffic(direction=ingress, port=8080, protocol=TCP)), Rule(id=7540c3b5-1f96-497a-a083-06d2f2a340c0, target=SG_test-master2, traffic=Traffic(direction=egress, port=8080, protocol=TCP)))
  - default: SecurityGroup(id=20065daa-8adf-4fd6-bd57-a8885f93b8c5, name=default, remotes=Rule(id=None, target=default, traffic=Traffic(direction=ingress, port=22, protocol=tcp)), Rule(id=None, target=default, traffic=Traffic(direction=egress, port=None, protocol=None)), Rule(id=None, target=default, traffic=Traffic(direction=ingress, port=None, protocol=icmp)), Rule(id=None, target=default, traffic=Traffic(direction=ingress, port=None, protocol=None)))
  - SG_k8s-test-1: SecurityGroup(id=2d7a5409-2e2f-4464-9bc7-0004d6f41d24, name=SG_k8s-test-1, remotes=)
  - Segment31: SecurityGroup(id=3929926b-c390-4a69-a8f6-b1c70b46743e, name=Segment31, remotes=Rule(id=None, target=Segment31, traffic=Traffic(direction=egress, port=None, protocol=tcp)), Rule(id=None, target=Segment31, traffic=Traffic(direction=ingress, port=None, protocol=tcp)))
  - SG_worker-10: SecurityGroup(id=40b0b171-e040-47f6-bf6e-96af45446cbd, name=SG_worker-10, remotes=)
  - SG_worker-9: SecurityGroup(id=57e160d0-e4d3-4650-9625-c3005a088a47, name=SG_worker-9, remotes=)
  - SG_test-worker-4: SecurityGroup(id=5ef88c59-6d96-42e5-8c06-4b6a687e4212, name=SG_test-worker-4, remotes=)
  - SG_worker-3: SecurityGroup(id=666f5f04-c7cc-4f63-a391-7f4a349981a9, name=SG_worker-3, remotes=)
  - SG_worker-6: SecurityGroup(id=73b59bf4-1055-4176-922a-5dc9c9339d96, name=SG_worker-6, remotes=)
  - SG_test-worker-2: SecurityGroup(id=86c2f6f1-76ce-425e-a152-7a035921f7e9, name=SG_test-worker-2, remotes=Rule(id=7acf631e-5da5-4299-b16f-eb308a0e8486, target=SG_test-master2, traffic=Traffic(direction=egress, port=3306, protocol=TCP)), Rule(id=8315a8f3-6f2d-47d9-ac9d-d35903067f9f, target=SG_test-master2, traffic=Traffic(direction=egress, port=53, protocol=UDP)), Rule(id=01723ef5-7c80-465a-bd47-a370a270ff66, target=SG_test-master2, traffic=Traffic(direction=egress, port=8080, protocol=TCP)), Rule(id=9861ccf0-d769-4447-ba40-b134939ff695, target=SG_test-master2, traffic=Traffic(direction=egress, port=53, protocol=TCP)), Rule(id=f8f67e28-475c-48ca-bf9f-6c904018335e, target=SG_test-master2, traffic=Traffic(direction=egress, port=9053, protocol=TCP)))
  - SG_worker-15: SecurityGroup(id=86eeee66-963a-4176-b9eb-9cbfdce612cc, name=SG_worker-15, remotes=)
  - workerSG: SecurityGroup(id=8e8640aa-474d-451d-afd8-c37c02d7fc86, name=workerSG, remotes=Rule(id=None, target=workerSG, traffic=Traffic(direction=egress, port=10250, protocol=tcp)), Rule(id=None, target=workerSG, traffic=Traffic(direction=egress, port=10259, protocol=tcp)), Rule(id=None, target=workerSG, traffic=Traffic(direction=ingress, port=53, protocol=udp)), Rule(id=None, target=workerSG, traffic=Traffic(direction=ingress, port=22, protocol=tcp)), Rule(id=None, target=workerSG, traffic=Traffic(direction=egress, port=9053, protocol=tcp)), Rule(id=None, target=workerSG, traffic=Traffic(direction=egress, port=53, protocol=udp)), Rule(id=None, target=workerSG, traffic=Traffic(direction=egress, port=22, protocol=tcp)), Rule(id=None, target=workerSG, traffic=Traffic(direction=ingress, port=10259, protocol=tcp)), Rule(id=None, target=workerSG, traffic=Traffic(direction=egress, port=2379, protocol=tcp)), Rule(id=None, target=workerSG, traffic=Traffic(direction=egress, port=179, protocol=tcp)), Rule(id=None, target=workerSG, traffic=Traffic(direction=egress, port=443, protocol=tcp)), Rule(id=None, target=workerSG, traffic=Traffic(direction=egress, port=6443, protocol=tcp)), Rule(id=None, target=workerSG, traffic=Traffic(direction=ingress, port=10250, protocol=tcp)), Rule(id=None, target=workerSG, traffic=Traffic(direction=egress, port=53, protocol=tcp)))
  - SG_worker-13: SecurityGroup(id=8f343489-0024-4287-8f45-b2f4f327d8ef, name=SG_worker-13, remotes=)
  - SG_worker-7: SecurityGroup(id=906ed4c9-457c-4c54-9785-751e57fed022, name=SG_worker-7, remotes=)
  - Segment32: SecurityGroup(id=995fa349-7fc8-4693-8548-3fc54b3d8132, name=Segment32, remotes=Rule(id=None, target=Segment32, traffic=Traffic(direction=egress, port=None, protocol=tcp)), Rule(id=None, target=Segment32, traffic=Traffic(direction=ingress, port=None, protocol=tcp)))
  - SG_worker-4: SecurityGroup(id=a94371c4-9120-4cfe-9d6d-4b77b1bfdbfb, name=SG_worker-4, remotes=)
  - SG_worker-11: SecurityGroup(id=b6b0811d-0ca7-47fb-8d1f-1f1fc8cfaafa, name=SG_worker-11, remotes=)
  - masterSG: SecurityGroup(id=c73d7f9b-5e7f-4eca-99fe-adc66c68f8a3, name=masterSG, remotes=Rule(id=None, target=masterSG, traffic=Traffic(direction=egress, port=10259, protocol=tcp)), Rule(id=None, target=masterSG, traffic=Traffic(direction=ingress, port=53, protocol=udp)), Rule(id=None, target=masterSG, traffic=Traffic(direction=ingress, port=10250, protocol=tcp)), Rule(id=None, target=masterSG, traffic=Traffic(direction=egress, port=9053, protocol=tcp)), Rule(id=None, target=masterSG, traffic=Traffic(direction=egress, port=53, protocol=udp)), Rule(id=None, target=masterSG, traffic=Traffic(direction=ingress, port=22, protocol=tcp)), Rule(id=None, target=masterSG, traffic=Traffic(direction=ingress, port=2379, protocol=tcp)), Rule(id=None, target=masterSG, traffic=Traffic(direction=ingress, port=53, protocol=tcp)), Rule(id=None, target=masterSG, traffic=Traffic(direction=egress, port=22, protocol=tcp)), Rule(id=None, target=masterSG, traffic=Traffic(direction=ingress, port=443, protocol=tcp)), Rule(id=None, target=masterSG, traffic=Traffic(direction=ingress, port=6443, protocol=tcp)), Rule(id=None, target=masterSG, traffic=Traffic(direction=ingress, port=10259, protocol=tcp)), Rule(id=None, target=masterSG, traffic=Traffic(direction=ingress, port=179, protocol=tcp)), Rule(id=None, target=masterSG, traffic=Traffic(direction=egress, port=443, protocol=tcp)), Rule(id=None, target=masterSG, traffic=Traffic(direction=egress, port=10250, protocol=tcp)))
  - SG_master: SecurityGroup(id=cbefa4c7-b55d-4bc5-b540-f91e7cbd481c, name=SG_master, remotes=)
  - SG_worker-5: SecurityGroup(id=d2bc2fe5-3e11-43ef-b9d7-b9cd81f02391, name=SG_worker-5, remotes=)
  - SG_worker-14: SecurityGroup(id=d2c9488e-b152-428e-92a2-418e34afd0b1, name=SG_worker-14, remotes=)
  - eddy-master: SecurityGroup(id=d603f39c-dac9-4f5e-96eb-aa0cf5d03e20, name=eddy-master, remotes=Rule(id=None, target=eddy-master, traffic=Traffic(direction=egress, port=53, protocol=udp)), Rule(id=None, target=eddy-master, traffic=Traffic(direction=ingress, port=53, protocol=udp)))
  - SG_test-master: SecurityGroup(id=d68a9b8d-6661-4ed8-97f8-fc30adb1bb7a, name=SG_test-master, remotes=)
  - SG_test-worker-1: SecurityGroup(id=dc44f4cb-cfa5-49bc-8fd8-4f49ff940c70, name=SG_test-worker-1, remotes=)
  - SG_worker-8: SecurityGroup(id=dda176fa-07ce-4855-a2ce-bd1f9ee34fb1, name=SG_worker-8, remotes=)
  - SG_worker-12: SecurityGroup(id=f08ee405-690f-400c-80d7-b06188cf9edd, name=SG_worker-12, remotes=)

Label Sets to Map Entries:
  - LabelSet(labels={'run': 'teastore-locust'}): MapEntry(match_nodes=(Node(name=test-worker-2)), select_pols=[], allow_pols=[ts-policy, ts-policy])
  - LabelSet(labels={'kubernetes.io/metadata.name': 'kube-system', 'k8s-app': 'kube-dns'}): MapEntry(match_nodes=(), select_pols=[], allow_pols=[ts-policy, ts-policy, ts-policy, ts-policy, ts-policy])
  - LabelSet(labels={'app': 'teastore'}): MapEntry(match_nodes=(Node(name=test-master2)), select_pols=[ts-policy, ts-policy, ts-policy, ts-policy, ts-policy, ts-policy, ts-policy, ts-policy, ts-policy, ts-policy, ts-policy, ts-policy, ts-policy, ts-policy], allow_pols=[ts-policy, ts-policy, ts-policy, ts-policy, ts-policy, ts-policy, ts-policy])
--------------

```
```
SG_test-worker-2 (86c2f6f1-76ce-425e-a152-7a035921f7e9)

	Egress 	IPv4 	TCP 	53 	- 	SG_test-master2 	- 	
	Egress 	IPv4 	TCP 	3306 (MYSQL) 	- 	SG_test-master2 	- 	
	Egress 	IPv4 	TCP 	8080 	- 	SG_test-master2 	- 	
	Egress 	IPv4 	TCP 	9053 	- 	SG_test-master2 	- 	
	Egress 	IPv4 	UDP 	53 (DNS) 	- 	SG_test-master2 
```
